//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LabData
{

    public partial class LabInsuranceType : XPObject
    {
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        int fserverID;
        public int serverID
        {
            get { return fserverID; }
            set { SetPropertyValue<int>("serverID", ref fserverID, value); }
        }
        int ffanniPrice;
        public int fanniPrice
        {
            get { return ffanniPrice; }
            set { SetPropertyValue<int>("fanniPrice", ref ffanniPrice, value); }
        }
        short ffranchises;
        public short franchises
        {
            get { return ffranchises; }
            set { SetPropertyValue<short>("franchises", ref ffranchises, value); }
        }
        [Association(@"LabVisitsReferencesLabInsuranceType")]
        public XPCollection<LabVisits> LabVisitsCollection { get { return GetCollection<LabVisits>("LabVisitsCollection"); } }
        [Association(@"TestPriceReferencesLabInsuranceType"), Aggregated]
        public XPCollection<TestPrice> TestPrices { get { return GetCollection<TestPrice>("TestPrices"); } }
    }

}
