//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LabData
{

    public partial class LabResults : XPObject
    {
        TestName ftestName;
        [Association(@"ResultsReferencesTestName")]
        public TestName testName
        {
            get { return ftestName; }
            set { SetPropertyValue<TestName>("testName", ref ftestName, value); }
        }
        LabVisits fvisitInfo;
        [Association(@"LabResultsReferencesLabVisits")]
        public LabVisits visitInfo
        {
            get { return fvisitInfo; }
            set { SetPropertyValue<LabVisits>("visitInfo", ref fvisitInfo, value); }
        }
        string fresult;
        public string result
        {
            get { return fresult; }
            set { SetPropertyValue<string>("result", ref fresult, value); }
        }
    }

}
