//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LabData
{

    public partial class LabVisits : XPObject
    {
        DateTime fvisitDate;
        public DateTime visitDate
        {
            get { return fvisitDate; }
            set { SetPropertyValue<DateTime>("visitDate", ref fvisitDate, value); }
        }
        LabInsuranceType finsType;
        [Association(@"LabVisitsReferencesLabInsuranceType")]
        public LabInsuranceType insType
        {
            get { return finsType; }
            set { SetPropertyValue<LabInsuranceType>("insType", ref finsType, value); }
        }
        PatientInfo fPatient;
        [Association(@"LabVisitsReferencesPatientInfo")]
        public PatientInfo Patient
        {
            get { return fPatient; }
            set { SetPropertyValue<PatientInfo>("Patient", ref fPatient, value); }
        }
        bool fpaid;
        public bool paid
        {
            get { return fpaid; }
            set { SetPropertyValue<bool>("paid", ref fpaid, value); }
        }
        bool fisFree;
        public bool isFree
        {
            get { return fisFree; }
            set { SetPropertyValue<bool>("isFree", ref fisFree, value); }
        }
        string fdescription;
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        bool fIsPrinted;
        public bool IsPrinted
        {
            get { return fIsPrinted; }
            set { SetPropertyValue<bool>("IsPrinted", ref fIsPrinted, value); }
        }
        int fPrice;
        public int Price
        {
            get { return fPrice; }
            set { SetPropertyValue<int>("Price", ref fPrice, value); }
        }
        LabUsers fuser;
        [Association(@"LabVisitsReferencesLabUsers")]
        public LabUsers user
        {
            get { return fuser; }
            set { SetPropertyValue<LabUsers>("user", ref fuser, value); }
        }
        [Association(@"TestCardReferencesLabVisits"), Aggregated]
        public XPCollection<TestCard> TestCards { get { return GetCollection<TestCard>("TestCards"); } }
    }

}
