//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LabData
{

    public partial class LabVisits : XPObject
    {
        DateTime fvisitDate;
        public DateTime visitDate
        {
            get { return fvisitDate; }
            set { SetPropertyValue<DateTime>("visitDate", ref fvisitDate, value); }
        }
        string fmelliCode;
        public string melliCode
        {
            get { return fmelliCode; }
            set { SetPropertyValue<string>("melliCode", ref fmelliCode, value); }
        }
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        DateTime fbirthday;
        public DateTime birthday
        {
            get { return fbirthday; }
            set { SetPropertyValue<DateTime>("birthday", ref fbirthday, value); }
        }
        string fphone;
        public string phone
        {
            get { return fphone; }
            set { SetPropertyValue<string>("phone", ref fphone, value); }
        }
        string faddress;
        [Size(SizeAttribute.Unlimited)]
        public string address
        {
            get { return faddress; }
            set { SetPropertyValue<string>("address", ref faddress, value); }
        }
        LabInsuranceType finsType;
        [Association(@"LabVisitsReferencesLabInsuranceType")]
        public LabInsuranceType insType
        {
            get { return finsType; }
            set { SetPropertyValue<LabInsuranceType>("insType", ref finsType, value); }
        }
        LabUsers fuser;
        [Association(@"LabVisitsReferencesLabUsers")]
        public LabUsers user
        {
            get { return fuser; }
            set { SetPropertyValue<LabUsers>("user", ref fuser, value); }
        }
        bool fpaid;
        public bool paid
        {
            get { return fpaid; }
            set { SetPropertyValue<bool>("paid", ref fpaid, value); }
        }
        bool fisFree;
        public bool isFree
        {
            get { return fisFree; }
            set { SetPropertyValue<bool>("isFree", ref fisFree, value); }
        }
        string fdescription;
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        bool fIsPrinted;
        public bool IsPrinted
        {
            get { return fIsPrinted; }
            set { SetPropertyValue<bool>("IsPrinted", ref fIsPrinted, value); }
        }
        [Association(@"TestListReferencesLabVisits"), Aggregated]
        public XPCollection<TestList> TestLists { get { return GetCollection<TestList>("TestLists"); } }
        [Association(@"LabResultsReferencesLabVisits"), Aggregated]
        public XPCollection<LabResults> LabResultsCollection { get { return GetCollection<LabResults>("LabResultsCollection"); } }
    }

}
