//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LabData
{

    public partial class PatientInfo : PersistentBase
    {
        int fOid;
        [Key(true)]
        public int Oid
        {
            get { return fOid; }
            set { SetPropertyValue<int>("Oid", ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        LabInsuranceType fInsurance;
        [Association(@"PatientInfoReferencesLabInsuranceType")]
        public LabInsuranceType Insurance
        {
            get { return fInsurance; }
            set { SetPropertyValue<LabInsuranceType>("Insurance", ref fInsurance, value); }
        }
        string fMelliCode;
        public string MelliCode
        {
            get { return fMelliCode; }
            set { SetPropertyValue<string>("MelliCode", ref fMelliCode, value); }
        }
        string fPhone;
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>("Phone", ref fPhone, value); }
        }
        DateTime? fBirthDate;
        public DateTime? BirthDate
        {
            get { return fBirthDate; }
            set { SetPropertyValue<DateTime?>("BirthDate", ref fBirthDate, value); }
        }
        string fAddress;
        [Size(SizeAttribute.Unlimited)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>("Address", ref fAddress, value); }
        }
        [Association(@"LabVisitsReferencesPatientInfo"), Aggregated]
        public IList<LabVisits> LabVisitsCollection { get { return GetList<LabVisits>("LabVisitsCollection"); } }
    }

}
