//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LabData
{

    public partial class TestGroup : XPObject
    {
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        int fprintOrder;
        public int printOrder
        {
            get { return fprintOrder; }
            set { SetPropertyValue<int>("printOrder", ref fprintOrder, value); }
        }
        [Association(@"TestNameReferencesTestGroup"), Aggregated]
        public XPCollection<TestName> TestNames { get { return GetCollection<TestName>("TestNames"); } }
    }

}
