//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LabData
{

    public partial class TestTemplate : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        byte fShortKey;
        public byte ShortKey
        {
            get { return fShortKey; }
            set { SetPropertyValue<byte>("ShortKey", ref fShortKey, value); }
        }
        [Association(@"TestNameReferencesTestTemplate")]
        public XPCollection<TestName> TestNames { get { return GetCollection<TestName>("TestNames"); } }
    }

}
