//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LabData
{

    public partial class TestPrice : XPObject
    {
        TestName ftestName;
        [Association(@"TestPriceReferencesTestName")]
        public TestName testName
        {
            get { return ftestName; }
            set { SetPropertyValue<TestName>("testName", ref ftestName, value); }
        }
        LabInsuranceType finsType;
        [Association(@"TestPriceReferencesLabInsuranceType")]
        public LabInsuranceType insType
        {
            get { return finsType; }
            set { SetPropertyValue<LabInsuranceType>("insType", ref finsType, value); }
        }
        int fprice;
        public int price
        {
            get { return fprice; }
            set { SetPropertyValue<int>("price", ref fprice, value); }
        }
    }

}
