//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LabData
{

    public partial class TestList : XPObject
    {
        LabVisits fvisitCode;
        [Association(@"TestListReferencesLabVisits")]
        public LabVisits visitCode
        {
            get { return fvisitCode; }
            set { SetPropertyValue<LabVisits>("visitCode", ref fvisitCode, value); }
        }
        TestName fParentTestName;
        [Association(@"TestListReferencesTestName")]
        public TestName ParentTestName
        {
            get { return fParentTestName; }
            set { SetPropertyValue<TestName>("ParentTestName", ref fParentTestName, value); }
        }
        int fPrice;
        public int Price
        {
            get { return fPrice; }
            set { SetPropertyValue<int>("Price", ref fPrice, value); }
        }
    }

}
