//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LabData
{

    public partial class TestName : XPObject
    {
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        string fcode;
        public string code
        {
            get { return fcode; }
            set { SetPropertyValue<string>("code", ref fcode, value); }
        }
        TestGroup fgroup;
        [Association(@"TestNameReferencesTestGroup")]
        public TestGroup group
        {
            get { return fgroup; }
            set { SetPropertyValue<TestGroup>("group", ref fgroup, value); }
        }
        TestName fparent;
        [Association(@"TestNameReferencesTestName")]
        public TestName parent
        {
            get { return fparent; }
            set { SetPropertyValue<TestName>("parent", ref fparent, value); }
        }
        byte fdataType;
        public byte dataType
        {
            get { return fdataType; }
            set { SetPropertyValue<byte>("dataType", ref fdataType, value); }
        }
        string funit;
        public string unit
        {
            get { return funit; }
            set { SetPropertyValue<string>("unit", ref funit, value); }
        }
        string fnlRange;
        public string nlRange
        {
            get { return fnlRange; }
            set { SetPropertyValue<string>("nlRange", ref fnlRange, value); }
        }
        string fdefValue;
        public string defValue
        {
            get { return fdefValue; }
            set { SetPropertyValue<string>("defValue", ref fdefValue, value); }
        }
        string fitmList;
        [Size(SizeAttribute.Unlimited)]
        public string itmList
        {
            get { return fitmList; }
            set { SetPropertyValue<string>("itmList", ref fitmList, value); }
        }
        int fprintOrder;
        public int printOrder
        {
            get { return fprintOrder; }
            set { SetPropertyValue<int>("printOrder", ref fprintOrder, value); }
        }
        int frealPrice;
        public int realPrice
        {
            get { return frealPrice; }
            set { SetPropertyValue<int>("realPrice", ref frealPrice, value); }
        }
        [Association(@"TestNameReferencesTestTemplate")]
        public XPCollection<TestTemplate> TestTemplates { get { return GetCollection<TestTemplate>("TestTemplates"); } }
        [Association(@"TestNameReferencesTestName"), Aggregated]
        public XPCollection<TestName> TestNameCollection { get { return GetCollection<TestName>("TestNameCollection"); } }
        [Association(@"TestPriceReferencesTestName"), Aggregated]
        public XPCollection<TestPrice> TestPrices { get { return GetCollection<TestPrice>("TestPrices"); } }
        [Association(@"ResultsReferencesTestName"), Aggregated]
        public XPCollection<LabResults> ResultsCollection { get { return GetCollection<LabResults>("ResultsCollection"); } }
        [Association(@"TestListReferencesTestName"), Aggregated]
        public XPCollection<TestList> TestLists { get { return GetCollection<TestList>("TestLists"); } }
    }

}
