//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DentData
{

    public partial class InsuranceTypes : XPObject
    {
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        int fserverID;
        public int serverID
        {
            get { return fserverID; }
            set { SetPropertyValue<int>(nameof(serverID), ref fserverID, value); }
        }
        [Association(@"VisitsReferencesInsuranceTypes")]
        public XPCollection<Visits> VisitsCollection { get { return GetCollection<Visits>(nameof(VisitsCollection)); } }
        [Association(@"PricesReferencesInsuranceTypes"), Aggregated]
        public XPCollection<Prices> PricesCollection { get { return GetCollection<Prices>(nameof(PricesCollection)); } }
    }

}
