//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DentData
{

    public partial class PatientInfo : XPObject
    {
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        string fmelliCode;
        public string melliCode
        {
            get { return fmelliCode; }
            set { SetPropertyValue<string>(nameof(melliCode), ref fmelliCode, value); }
        }
        DateTime fbirthDate;
        public DateTime birthDate
        {
            get { return fbirthDate; }
            set { SetPropertyValue<DateTime>(nameof(birthDate), ref fbirthDate, value); }
        }
        string fphone;
        public string phone
        {
            get { return fphone; }
            set { SetPropertyValue<string>(nameof(phone), ref fphone, value); }
        }
        bool fIsBlackList;
        public bool IsBlackList
        {
            get { return fIsBlackList; }
            set { SetPropertyValue<bool>(nameof(IsBlackList), ref fIsBlackList, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
        [Association(@"VisitsReferencesPatientInfo"), Aggregated]
        public XPCollection<Visits> VisitsCollection { get { return GetCollection<Visits>(nameof(VisitsCollection)); } }
    }

}
