//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DentData
{

    public partial class Prices : XPObject
    {
        InsuranceTypes fInsurance;
        [Association(@"PricesReferencesInsuranceTypes")]
        public InsuranceTypes Insurance
        {
            get { return fInsurance; }
            set { SetPropertyValue<InsuranceTypes>(nameof(Insurance), ref fInsurance, value); }
        }
        Services fService;
        [Association(@"PricesReferencesServices")]
        public Services Service
        {
            get { return fService; }
            set { SetPropertyValue<Services>(nameof(Service), ref fService, value); }
        }
        int fPrice1;
        public int Price1
        {
            get { return fPrice1; }
            set { SetPropertyValue<int>(nameof(Price1), ref fPrice1, value); }
        }
        int fPrice2;
        public int Price2
        {
            get { return fPrice2; }
            set { SetPropertyValue<int>(nameof(Price2), ref fPrice2, value); }
        }
    }

}
