//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DentData
{

    public partial class ServiceList : XPObject
    {
        Services fServiceName;
        [Association(@"ServiceListReferencesServices")]
        public Services ServiceName
        {
            get { return fServiceName; }
            set { SetPropertyValue<Services>(nameof(ServiceName), ref fServiceName, value); }
        }
        Visits fVisitName;
        [Association(@"ServiceListReferencesVisits")]
        public Visits VisitName
        {
            get { return fVisitName; }
            set { SetPropertyValue<Visits>(nameof(VisitName), ref fVisitName, value); }
        }
        int fNumber;
        public int Number
        {
            get { return fNumber; }
            set { SetPropertyValue<int>(nameof(Number), ref fNumber, value); }
        }
    }

}
