//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DentData
{

    public partial class Services : XPObject
    {
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        int ftime;
        public int time
        {
            get { return ftime; }
            set { SetPropertyValue<int>(nameof(time), ref ftime, value); }
        }
        int fInsurancePrice;
        public int InsurancePrice
        {
            get { return fInsurancePrice; }
            set { SetPropertyValue<int>(nameof(InsurancePrice), ref fInsurancePrice, value); }
        }
        int fnonInsurancePrice;
        public int nonInsurancePrice
        {
            get { return fnonInsurancePrice; }
            set { SetPropertyValue<int>(nameof(nonInsurancePrice), ref fnonInsurancePrice, value); }
        }
        [Association(@"ServiceListReferencesServices"), Aggregated]
        public XPCollection<ServiceList> ServiceLists { get { return GetCollection<ServiceList>(nameof(ServiceLists)); } }
        [Association(@"PricesReferencesServices"), Aggregated]
        public XPCollection<Prices> PricesCollection { get { return GetCollection<Prices>(nameof(PricesCollection)); } }
    }

}
