//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DentData
{

    public partial class Users : XPObject
    {
        string fusername;
        public string username
        {
            get { return fusername; }
            set { SetPropertyValue<string>(nameof(username), ref fusername, value); }
        }
        string fpassword;
        public string password
        {
            get { return fpassword; }
            set { SetPropertyValue<string>(nameof(password), ref fpassword, value); }
        }
        string frealname;
        public string realname
        {
            get { return frealname; }
            set { SetPropertyValue<string>(nameof(realname), ref frealname, value); }
        }
        string fphone;
        public string phone
        {
            get { return fphone; }
            set { SetPropertyValue<string>(nameof(phone), ref fphone, value); }
        }
        byte[] fphoto;
        [MemberDesignTimeVisibility(true)]
        public byte[] photo
        {
            get { return fphoto; }
            set { SetPropertyValue<byte[]>(nameof(photo), ref fphoto, value); }
        }
        string fgroup;
        public string group
        {
            get { return fgroup; }
            set { SetPropertyValue<string>(nameof(group), ref fgroup, value); }
        }
        [Association(@"VisitsReferencesDentUsers")]
        public XPCollection<Visits> VisitsCollection { get { return GetCollection<Visits>(nameof(VisitsCollection)); } }
    }

}
