//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace HCMData
{

    public partial class DefEquip : XPObject
    {
        Equipments fEquipName;
        [Association(@"DefEquipReferencesEquipments")]
        public Equipments EquipName
        {
            get { return fEquipName; }
            set { SetPropertyValue<Equipments>("EquipName", ref fEquipName, value); }
        }
        HealthServices fService;
        [Association(@"DefEquipReferencesHealthServices")]
        public HealthServices Service
        {
            get { return fService; }
            set { SetPropertyValue<HealthServices>("Service", ref fService, value); }
        }
        int fCount;
        public int Count
        {
            get { return fCount; }
            set { SetPropertyValue<int>("Count", ref fCount, value); }
        }
    }

}
