//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace HCMData
{

    public partial class HealthServices : XPObject
    {
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        string fgroup;
        public string group
        {
            get { return fgroup; }
            set { SetPropertyValue<string>("group", ref fgroup, value); }
        }
        HealthServices fparent;
        [Association(@"HealthServicesReferencesHealthServices")]
        public HealthServices parent
        {
            get { return fparent; }
            set { SetPropertyValue<HealthServices>("parent", ref fparent, value); }
        }
        byte[] fimage;
        [MemberDesignTimeVisibility(true)]
        public byte[] image
        {
            get { return fimage; }
            set { SetPropertyValue<byte[]>("image", ref fimage, value); }
        }
        bool fCanReserve;
        public bool CanReserve
        {
            get { return fCanReserve; }
            set { SetPropertyValue<bool>("CanReserve", ref fCanReserve, value); }
        }
        int fReservePrice;
        public int ReservePrice
        {
            get { return fReservePrice; }
            set { SetPropertyValue<int>("ReservePrice", ref fReservePrice, value); }
        }
        bool fShowInReport;
        public bool ShowInReport
        {
            get { return fShowInReport; }
            set { SetPropertyValue<bool>("ShowInReport", ref fShowInReport, value); }
        }
        string fProviderRole;
        public string ProviderRole
        {
            get { return fProviderRole; }
            set { SetPropertyValue<string>("ProviderRole", ref fProviderRole, value); }
        }
        [Association(@"VisitsReferencesServices")]
        public XPCollection<Visits> VisitsCollection { get { return GetCollection<Visits>("VisitsCollection"); } }
        [Association(@"PricesReferencesServices"), Aggregated]
        public XPCollection<Prices> PricesCollection { get { return GetCollection<Prices>("PricesCollection"); } }
        [Association(@"HealthServicesReferencesHealthServices"), Aggregated]
        public XPCollection<HealthServices> HealthServicesCollection { get { return GetCollection<HealthServices>("HealthServicesCollection"); } }
        [Association(@"ReservesReferencesHealthServices"), Aggregated]
        public XPCollection<Reserves> ReservesCollection { get { return GetCollection<Reserves>("ReservesCollection"); } }
        [Association(@"DefEquipReferencesHealthServices"), Aggregated]
        public XPCollection<DefEquip> DefEquips { get { return GetCollection<DefEquip>("DefEquips"); } }
    }

}
