//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace HCMData
{

    public partial class PatientInfo : XPObject
    {
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        string fmelliCode;
        public string melliCode
        {
            get { return fmelliCode; }
            set { SetPropertyValue<string>("melliCode", ref fmelliCode, value); }
        }
        string fmobile;
        public string mobile
        {
            get { return fmobile; }
            set { SetPropertyValue<string>("mobile", ref fmobile, value); }
        }
        insuranceType finsurance;
        [Association(@"PatientInfoReferencesinsuranceType")]
        public insuranceType insurance
        {
            get { return finsurance; }
            set { SetPropertyValue<insuranceType>("insurance", ref finsurance, value); }
        }
        [Association(@"VisitsReferencesPatientInfo"), Aggregated]
        public XPCollection<Visits> VisitsCollection { get { return GetCollection<Visits>("VisitsCollection"); } }
        [Association(@"ReservesReferencesPatientInfo"), Aggregated]
        public XPCollection<Reserves> ReservesCollection { get { return GetCollection<Reserves>("ReservesCollection"); } }
    }

}
