//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace HCMData
{

    public partial class Prices : XPObject
    {
        insuranceType finsType;
        [Association(@"PricesReferencesinsuranceType")]
        public insuranceType insType
        {
            get { return finsType; }
            set { SetPropertyValue<insuranceType>("insType", ref finsType, value); }
        }
        HealthServices fservice;
        [Association(@"PricesReferencesServices")]
        public HealthServices service
        {
            get { return fservice; }
            set { SetPropertyValue<HealthServices>("service", ref fservice, value); }
        }
        int fprice1;
        public int price1
        {
            get { return fprice1; }
            set { SetPropertyValue<int>("price1", ref fprice1, value); }
        }
        int fprice2;
        public int price2
        {
            get { return fprice2; }
            set { SetPropertyValue<int>("price2", ref fprice2, value); }
        }
    }

}
