//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace HCMData
{

    public partial class RemoteBill : XPObject
    {
        string fServiceType;
        public string ServiceType
        {
            get { return fServiceType; }
            set { SetPropertyValue<string>("ServiceType", ref fServiceType, value); }
        }
        string fMelliCode;
        public string MelliCode
        {
            get { return fMelliCode; }
            set { SetPropertyValue<string>("MelliCode", ref fMelliCode, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        int fRemoteBillId;
        public int RemoteBillId
        {
            get { return fRemoteBillId; }
            set { SetPropertyValue<int>("RemoteBillId", ref fRemoteBillId, value); }
        }
        int fPrice;
        public int Price
        {
            get { return fPrice; }
            set { SetPropertyValue<int>("Price", ref fPrice, value); }
        }
        int fInsId;
        public int InsId
        {
            get { return fInsId; }
            set { SetPropertyValue<int>("InsId", ref fInsId, value); }
        }
        bool fIsPaid;
        public bool IsPaid
        {
            get { return fIsPaid; }
            set { SetPropertyValue<bool>("IsPaid", ref fIsPaid, value); }
        }
    }

}
