//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace HCMData
{

    public partial class Reserves : XPObject
    {
        PatientInfo fPatient;
        [Association(@"ReservesReferencesPatientInfo")]
        public PatientInfo Patient
        {
            get { return fPatient; }
            set { SetPropertyValue<PatientInfo>("Patient", ref fPatient, value); }
        }
        HealthServices fService;
        [Association(@"ReservesReferencesHealthServices")]
        public HealthServices Service
        {
            get { return fService; }
            set { SetPropertyValue<HealthServices>("Service", ref fService, value); }
        }
        DateTime fAdmitDate;
        public DateTime AdmitDate
        {
            get { return fAdmitDate; }
            set { SetPropertyValue<DateTime>("AdmitDate", ref fAdmitDate, value); }
        }
    }

}
