//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace HCMData
{

    public partial class Users : XPObject
    {
        string fusername;
        public string username
        {
            get { return fusername; }
            set { SetPropertyValue<string>("username", ref fusername, value); }
        }
        string fpassword;
        public string password
        {
            get { return fpassword; }
            set { SetPropertyValue<string>("password", ref fpassword, value); }
        }
        string frealname;
        public string realname
        {
            get { return frealname; }
            set { SetPropertyValue<string>("realname", ref frealname, value); }
        }
        string fphone;
        public string phone
        {
            get { return fphone; }
            set { SetPropertyValue<string>("phone", ref fphone, value); }
        }
        byte[] fphoto;
        [MemberDesignTimeVisibility(true)]
        public byte[] photo
        {
            get { return fphoto; }
            set { SetPropertyValue<byte[]>("photo", ref fphoto, value); }
        }
        string fgroup;
        public string group
        {
            get { return fgroup; }
            set { SetPropertyValue<string>("group", ref fgroup, value); }
        }
        DateTime flastLogin;
        public DateTime lastLogin
        {
            get { return flastLogin; }
            set { SetPropertyValue<DateTime>("lastLogin", ref flastLogin, value); }
        }
        [Association(@"VisitsReferencesUsers")]
        public XPCollection<Visits> VisitsCollection { get { return GetCollection<Visits>("VisitsCollection"); } }
    }

}
