//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace HCMData
{

    public partial class Visits : XPObject
    {
        DateTime fvisitDate;
        public DateTime visitDate
        {
            get { return fvisitDate; }
            set { SetPropertyValue<DateTime>("visitDate", ref fvisitDate, value); }
        }
        PatientInfo fpatient;
        [Association(@"VisitsReferencesPatientInfo")]
        public PatientInfo patient
        {
            get { return fpatient; }
            set { SetPropertyValue<PatientInfo>("patient", ref fpatient, value); }
        }
        insuranceType finsType;
        [Association(@"VisitsReferencesinsuranceType")]
        public insuranceType insType
        {
            get { return finsType; }
            set { SetPropertyValue<insuranceType>("insType", ref finsType, value); }
        }
        HealthServices fservice;
        [Association(@"VisitsReferencesServices")]
        public HealthServices service
        {
            get { return fservice; }
            set { SetPropertyValue<HealthServices>("service", ref fservice, value); }
        }
        int fprice;
        public int price
        {
            get { return fprice; }
            set { SetPropertyValue<int>("price", ref fprice, value); }
        }
        bool fisFullPrice;
        public bool isFullPrice
        {
            get { return fisFullPrice; }
            set { SetPropertyValue<bool>("isFullPrice", ref fisFullPrice, value); }
        }
        Users fuser;
        [Association(@"VisitsReferencesUsers")]
        public Users user
        {
            get { return fuser; }
            set { SetPropertyValue<Users>("user", ref fuser, value); }
        }
        Personnel fPersonnel;
        [Association(@"VisitsReferencesPersonnel")]
        public Personnel Personnel
        {
            get { return fPersonnel; }
            set { SetPropertyValue<Personnel>("Personnel", ref fPersonnel, value); }
        }
        [Association(@"EquipmentListReferencesVisits"), Aggregated]
        public XPCollection<EquipmentList> EquipmentLists { get { return GetCollection<EquipmentList>("EquipmentLists"); } }
    }

}
